name: Deploy prod_frontend
on:
  workflow_dispatch:

jobs:
  create_update_production_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set up git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Create/update branch from frontend build directory
        id: frontend_subtree
        run: |
          git checkout main
          git subtree split --branch dev_frontend --prefix frontend/build/
